### ISSUE TITLE
Implement Multisig Wallet_2 section Multi-sig journey

### ISSUE THREAD

**Issue by hnquan8** [Beraji-Labs/desig-home#10]
A Web UI has 6 card and can scroll horizontally

![Image](https://github.com/Desig-Labs/desig-home/assets/135295387/eff89d11-dfb8-432a-8083-9dba5beae52c)

A Mobile UI has 6 card and can scroll horizontally

![Image](https://github.com/Desig-Labs/desig-home/assets/135295387/580dadc6-83db-4f67-9040-b16baa4890f3)

**Comment by hnquan8** [comment]
I Implemented Web UI 
![Image](https://github.com/Desig-Labs/desig-home/assets/135295387/4f1b52cd-d5f5-48a6-b42a-c77a82ff75a5)

**Comment by hnquan8** [comment]
I Implemented Mobile UI (fixed)



![Image](https://github.com/Desig-Labs/desig-home/assets/135295387/2ef8d32d-5cb8-4d07-b291-4c1ad3513e94)

**Comment by ethanpx** [comment]
- Mr. Quân said that the design wants to create a mobile card similar to the image below. 

![Image](https://github.com/Desig-Labs/desig-home/assets/81727176/f841ac69-919d-4159-9a96-959f41b62d2c)

- LGTM for now!
