### ISSUE TITLE
Implement Multisig Wallet_4 section More Feature and Multi-sig Management

### ISSUE THREAD

**Issue by hnquan8** [Beraji-Labs/desig-home#12]
Web UI has : 
- More feature section : 4 cards
- Multi-sig Management

![Image](https://github.com/Desig-Labs/desig-home/assets/135295387/e63f3eef-4c3f-4bf0-a2b8-d141b7ec97d6)

Mobile UI has :
- More feature section : 4 cards
- Multi-sig Management

![Image](https://github.com/Desig-Labs/desig-home/assets/135295387/a9062104-c362-4927-8b01-767b6881a14b)

**Comment by hnquan8** [comment]
I implemented a Web UI: 
- More feature 
![Image](https://github.com/Desig-Labs/desig-home/assets/135295387/a5f11a43-2621-4a48-9946-2449385ed648)
- Multi-sig Management
![Image](https://github.com/Desig-Labs/desig-home/assets/135295387/0d9c2e5c-3d60-4388-80db-8eec01840f79)

**Comment by hnquan8** [comment]
I implemented a Mobile UI
- More feature
![Image](https://github.com/Desig-Labs/desig-home/assets/135295387/9a623f53-85c6-4920-9c56-efb8bfb6fdeb)
- Multi-sig Management
![Image](https://github.com/Desig-Labs/desig-home/assets/135295387/d041147a-d757-4d06-99cd-b20e11b163f7)

**Comment by ethanpx** [comment]
lgtm
