### ISSUE TITLE
Implement Home_7 Future of multisig

### ISSUE THREAD

**Issue by ducmanh1101** [Beraji-Labs/desig-home#15]

**Comment by ducmanh1101** [comment]
Bản web


![Image](https://github.com/Desig-Labs/desig-home/assets/142195756/33219d6f-82a2-4172-9dfe-22f28b6e5b40)

Mobile


![Image](https://github.com/Desig-Labs/desig-home/assets/142195756/5b037687-6fef-4789-8c99-540fafed829f)

**Comment by ethanpx** [comment]
- align description
- Change mail to -> talk to us

**Comment by ducmanh1101** [comment]
fix text and align in mobile


![Image](https://github.com/Desig-Labs/desig-home/assets/142195756/126b9846-0a7f-4a71-9a22-9a46302b71ae)

**Comment by michael-duo** [comment]
LGTM
