### ISSUE TITLE
Implement Home_6 footer

### ISSUE THREAD

**Issue by michael-duo** [Beraji-Labs/desig-home#3]
![Image](https://github.com/Desig-Labs/desig-home/assets/83624415/85485687-9671-48cb-9890-1328cdbbd539)

**Comment by ducmanh1101** [comment]
Bản web: 


![Image](https://github.com/Desig-Labs/desig-home/assets/142195756/c191dd91-8112-4fa6-825c-44cc0c85ebf3)

Bản Mobile


![Image](https://github.com/Desig-Labs/desig-home/assets/142195756/682c72cb-04e3-4009-99c2-270e96721453)

**Comment by ethanpx** [comment]
LGTM

**Comment by ducmanh1101** [comment]
need form mail?


![Image](https://github.com/Desig-Labs/desig-home/assets/142195756/8e1da3a1-311c-4ee3-bb91-8cc9b08097dd)
