### ISSUE TITLE
Implement Home_5 Our Vision for the Future

### ISSUE THREAD

**Issue by michael-duo** [Beraji-Labs/desig-home#5]
![Image](https://github.com/Desig-Labs/desig-home/assets/83624415/1030b225-5270-4917-b18f-61416f2bde37)

**Comment by ducmanh1101** [comment]
Bản web

![Image](https://github.com/Desig-Labs/desig-home/assets/142195756/8f81c1a5-802e-4383-862b-25d90a230bea)



Bản mobile: 

![Image](https://github.com/Desig-Labs/desig-home/assets/142195756/85d88a64-b20b-4ab3-9378-62557bfd3c30)

**Comment by ethanpx** [comment]
LGTM
