### ISSUE TITLE
Implement Download page

### ISSUE THREAD

**Issue by michael-duo** [Beraji-Labs/desig-home#6]
UI Web: 
Download page have a banner and 3 cards: 
- Download for Chrom
- Download for IOS
- Download from Android

![Image](https://github.com/Desig-Labs/desig-home/assets/83624415/d64bd13d-e422-403f-977e-ced65efaf9f1)

UI mobile:
Download page have a banner and 3 cards: 
- Download for Chrom
- Download for IOS
- Download from Android

![Image](https://github.com/Desig-Labs/desig-home/assets/135295387/d814ab9a-697d-4b9b-a971-b4e0f843e644)

**Comment by hnquan8** [comment]
I implement a web UI
![Image](https://github.com/Desig-Labs/desig-home/assets/135295387/63fc989d-bd58-4caf-a73d-2d19b5e60828)
I implement a mobile UI
![Image](https://github.com/Desig-Labs/desig-home/assets/135295387/f165bf71-6592-4dc3-b08d-ddfcdc9d5046)

**Comment by ethanpx** [comment]
The banner image wrong ratio on the mobile

* Web: 
![Image](https://github.com/Desig-Labs/desig-home/assets/81727176/b4ab3365-22ec-447e-9ce8-6fc2bd0bf8e5)


* Design:
![Image](https://github.com/Desig-Labs/desig-home/assets/81727176/ca61f555-4f51-4736-93d9-41c664f14bc6)
