### ISSUE TITLE
Implement Multisig Wallet_1 header + banner

### ISSUE THREAD

**Issue by hnquan8** [Beraji-Labs/desig-home#9]
UI Web: 
- Header has a logo brand, menu and button Get Early Access
- Banner has title, description and button Get Early Access

![Image](https://github.com/Desig-Labs/desig-home/assets/135295387/480df742-6d68-4f6c-8a36-83ba938f638b)

UI Mobile:
- Header has a logo brand and button menu
- Banner has title, description and button Get Early Access

![Image](https://github.com/Desig-Labs/desig-home/assets/135295387/cd170790-ee7f-49f4-b506-f446b4b9d2d5)

**Comment by hnquan8** [comment]
I implemented a web UI

![Image](https://github.com/Desig-Labs/desig-home/assets/135295387/3d18b2a8-7108-43c0-9e75-f83fccf2e243)

**Comment by hnquan8** [comment]
I implemented a mobile UI

![Image](https://github.com/Desig-Labs/desig-home/assets/135295387/0b6db5cd-54f4-4225-8430-958134eee37a)

**Comment by ethanpx** [comment]
lgtm
